---
- hosts: all
  sudo: true
  vars:
    rvm1_rubies:
      - "{{ jruby_version }}"
    rvm1_install_flags: '--auto-dotfiles --user-install --with-gems="bundler"'
    rvm1_install_path: '/home/{{ ansible_ssh_user }}/.rvm'
    rvm1_user: "{{ ansible_ssh_user }}"

  roles:
    - { role: common, sudo: yes }
    - { role: logstash, sudo: yes }
    - { role: rvm_io.rvm1-ruby, sudo: yes }

  tasks:
    - name: Main | Ensure that our filter is sourced by our installation of LogStash
      lineinfile: >
        dest=/opt/logstash/Gemfile
        line='gem "logstash-filter-fix_protocol", :path => "/vagrant/"'

    - name: Main | Make sure that logstash installation is owned by vagrant
      file: path=/opt/logstash state=directory mode=0755 owner={{ ansible_ssh_user }} recurse=yes

    - name: Main | Symlink logstash executable to /usr/bin
      file: src=/opt/logstash/bin/logstash dest=/usr/bin/logstash state=link

    - name: Main | Install our LogStash Plugin
      shell: bin/plugin install --no-verify chdir=/opt/logstash/

    - name: Main | Install the File LogStash Plugin
      shell: bin/plugin install logstash-input-file chdir=/opt/logstash/
